

translation = {
    'trees': 'Decision Trees',
    'ai-mul-trees': 'Decision Trees',
    'randomforest': 'Random Forest',
    'ai-mul-randomforest': 'Random Forest',
    'svm': 'Support Vector Machines',
    'ai-mul-svm': 'Support Vector Machines',
    'knn': 'K-Nearest Neighbors',
    'ai-mul-knn': 'K-Nearest Neighbors',
    'ai-mul-lr': 'Linear/Logistic Regression',
    'neuralnetworks': 'Neural Networks',
    'ai-mul-neuralnetworks': 'Neural Networks',
    'reinforcement-learning': 'Reinforcement Learning',
    'genetic': 'Evolutionary and Genetic Algorithms',
    'ai-mul-genetic': 'Evolutionary and Genetic Algorithms',
    'nlp': 'Natural Language Processing',
    'ai-mul-llm': 'Natural Language Processing',
    'automatonlearning': 'Automaton Learning',
    'baysianinference': 'Bayesian Inference',
    'clustering': 'Clustering',
    'ai-mul-clustering': 'Clustering',
    'datamining': 'Data Mining',
    'ai-mul-datamining': 'Data Mining',
    'ai-mul-adaboost': 'AdaBoost',
    'ai-mul-bagging': 'Bagging',
    'ai-mul-centroid': 'Nearest Centroid',
    'ai-mul-gaussian': 'Gaussian Processes',
    'ai-mul-mcts': 'Monte Carlo Tree Search',
    'ai-mul-naive': 'Naive Bayes',
    'ai-mul-passiveaggresive': 'Passive Aggressive',
    'ai-mul-ridge': 'Ridge Regression',
    'ai-mul-sgd': 'Stochastic Gradient Descent',
    'ai-mul-smac': 'SMAC',
    'ai-multiple': 'Mult. AI-Techniques',
    'ai-custom': 'Custom Algorithm',
    'ai-other': 'Other',
}
